version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: chat-backend
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: production
      SECRET_KEY: SECRETKEY
      JWT_SECRET_KEY: JWTSECRETKEY
      GOOGLE_CLOUD_PROJECT: google-id
      GOOGLE_APPLICATION_CREDENTIALS: /path/to-account-file.json
    volumes:
      - ./service-account-file.json:/app/service-account-file.json
    networks:
      - chat-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "8081:8080"
    volumes:
      - ./frontend:/app
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
